// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dftwowucrwlgkvodoblt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmdHdvd3VjcndsZ2t2b2RvYmx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzg2MTIsImV4cCI6MjA2NTcxNDYxMn0.nQXZRo_jnRXpZWlPNZITpxyBp8xrO9JPGhJSbXclxf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);